### ISSUE TITLE
Create @bitsongjs/utils package

### ISSUE THREAD

**Issue by DavideSegullo** [bitsongofficial/bitsongjs#11]
We could create a package to manage utilities, for example for data conversions or to read IBC tokens

**Comment by angelorc** [comment]
totally agree...even constants (exponent, microdenom, denom...) must be there

**Comment by DavideSegullo** [comment]
> totally agree...even constants (exponent, microdenom, denom...) must be there

We can export them from the [chain registry](https://github.com/cosmos/chain-registry/blob/master/bitsong/assetlist.json)

**Comment by DavideSegullo** [comment]
We should add a utility to generate the merkledrop file with proofs like we do in the go-bitsong cli

**Comment by angelorc** [comment]
Yes I agree. Something like this? https://github.com/Mirror-Protocol/mirror-airdrop/blob/main/src/Airdrop.ts

**Comment by DavideSegullo** [comment]
> Yes I agree. Something like this? https://github.com/Mirror-Protocol/mirror-airdrop/blob/main/src/Airdrop.ts

Yes, I will use it as a reference
